"""Initial Migration

Revision ID: 204a5fd495ea
Revises: 264e74944dc9
Create Date: 2020-05-09 23:09:31.080208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204a5fd495ea'
down_revision = '264e74944dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_slug_key', 'posts', type_='unique')
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_unique_constraint('posts_slug_key', 'posts', ['slug'])
    # ### end Alembic commands ###
