"""Initial Migration

Revision ID: 264e74944dc9
Revises: a4e08a17b796
Create Date: 2020-05-09 22:57:39.174183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264e74944dc9'
down_revision = 'a4e08a17b796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
