"""empty message

Revision ID: 33bdf88bed20
Revises: cdbac9e281ac
Create Date: 2020-05-13 00:10:00.938000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bdf88bed20'
down_revision = 'cdbac9e281ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
