"""Initial Migration

Revision ID: 50ca4ebe1c70
Revises: 6eae32f66391
Create Date: 2020-05-11 02:16:04.050690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ca4ebe1c70'
down_revision = '6eae32f66391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscribers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.drop_column('subscribers', 'user_id')
    # ### end Alembic commands ###
