"""Initial Migration

Revision ID: 6eae32f66391
Revises: 204a5fd495ea
Create Date: 2020-05-09 23:30:47.654240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eae32f66391'
down_revision = '204a5fd495ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
