"""Initial Migration

Revision ID: 76575ced7d19
Revises: 3b88cc040e65
Create Date: 2020-05-09 17:32:10.289441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76575ced7d19'
down_revision = '3b88cc040e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=180), nullable=True))
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
