"""Initial Migration

Revision ID: 84c4a7ddb895
Revises: 
Create Date: 2020-05-12 20:06:24.228008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c4a7ddb895'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_title_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('posts_title_key', 'posts', ['title'])
    # ### end Alembic commands ###
